services:
  - type: web
    name: bot-520-vagas
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      # Adicione suas variaveis no painel do Render:
      # TELEGRAM_TOKEN
      # GROQ_API_KEY
      # WEBHOOK_URL
